### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError

### ISSUE THREAD

**Issue by voku** [wapmorgan/PhpDeprecationDetector#66]
Hi, I see this error with the new version 2.0.28.

`PHP Fatal error:  Uncaught TypeError: Argument 1 passed to wapmorgan\PhpCodeFixer\PhpCodeFixer::trimSpaces() must be of the type array, string given.`

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to wapmorgan\PhpCodeFixer\PhpCodeFixer::trimSpaces() must be of the type array, string given, called in phar:///home/lmoelleken/meerx/Framework/thirdparty/phpdd.phar/data/implode_param_order_check.php on line 17 and defined in phar:///home/lmoelleken/meerx/Framework/thirdparty/phpdd.phar/src/PhpCodeFixer.php:275
Stack trace:
#0 phar:///home/lmoelleken/meerx/Framework/thirdparty/phpdd.phar/data/implode_param_order_check.php(17): wapmorgan\PhpCodeFixer\PhpCodeFixer::trimSpaces()
#1 phar:///home/lmoelleken/meerx/Framework/thirdparty/phpdd.phar/src/PhpCodeFixer.php(301): wapmorgan\PhpCodeFixer\implode_param_order_check()
#2 phar:///home/lmoelleken/meerx/Framework/thirdparty/phpdd.phar/src/PhpCodeFixer.php(544): wapmorgan\PhpCodeFixer\PhpCodeFixer::callFunctionUsageChecker()
#3 phar:///home/lmoelleken/meerx/Framework/thirdparty/phpdd.phar/src/PhpCodeFixer.php(219): wapmorgan\PhpCodeFixer\PhpCodeFixer->analyzeFunctionsUsage()
#4 phar:///home/lmoelleken/meerx/Framework/thirdpart in phar:///home/lmoelleken/meerx/Framework/thirdparty/phpdd.phar/src/PhpCodeFixer.php on line 275
```

**Comment by wapmorgan** [comment]
Can you provide code?

**Comment by voku** [comment]
I used `strace` to detect the affected file, and it's this file: https://github.com/scssphp/scssphp/blob/master/src/Compiler.php

**Comment by wapmorgan** [comment]
In 2.0.29

**Comment by voku** [comment]
Tested, now it's working. Thanks.
